// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9JBLM-XmpIeCaUtgyu7AgQWvHr2ME_I',
    appId: '1:717428515537:web:97114b4296118749261bf0',
    messagingSenderId: '717428515537',
    projectId: 'admit-ai-1badd',
    authDomain: 'admit-ai-1badd.firebaseapp.com',
    storageBucket: 'admit-ai-1badd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWcMMqAX1UwH-WmDjBkeGIQGhOoYDDfT8',
    appId: '1:717428515537:android:c0077a9213864397261bf0',
    messagingSenderId: '717428515537',
    projectId: 'admit-ai-1badd',
    storageBucket: 'admit-ai-1badd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuc_6MeSq7n30BB5DsZOppLAiFOrU3Mn4',
    appId: '1:717428515537:ios:7dc9777ab6b7025b261bf0',
    messagingSenderId: '717428515537',
    projectId: 'admit-ai-1badd',
    storageBucket: 'admit-ai-1badd.firebasestorage.app',
    iosBundleId: 'com.example.admitAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuc_6MeSq7n30BB5DsZOppLAiFOrU3Mn4',
    appId: '1:717428515537:ios:7dc9777ab6b7025b261bf0',
    messagingSenderId: '717428515537',
    projectId: 'admit-ai-1badd',
    storageBucket: 'admit-ai-1badd.firebasestorage.app',
    iosBundleId: 'com.example.admitAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9JBLM-XmpIeCaUtgyu7AgQWvHr2ME_I',
    appId: '1:717428515537:web:9a26f82a497d3ec5261bf0',
    messagingSenderId: '717428515537',
    projectId: 'admit-ai-1badd',
    authDomain: 'admit-ai-1badd.firebaseapp.com',
    storageBucket: 'admit-ai-1badd.firebasestorage.app',
  );
}
